import {
  Vehicle,
  Customer,
  Booking,
  Payment,
  MaintenanceRecord,
  BusinessSettings,
  DashboardStats,
  MonthlyRevenue,
  VehicleUtilization,
} from "../types";

// ==========================================
// VEHICLES
// ==========================================
export const vehicles: Vehicle[] = [
  {
    id: "v1",
    brand: "Maruti Suzuki",
    model: "Swift",
    year: 2023,
    category: "Hatchback",
    registrationNumber: "KA-01-AB-1234",
    fuelType: "Petrol",
    transmission: "Manual",
    status: "Available",
    pricePerDay: 1200,
    imageUrl: "/vehicles/swift.jpg",
    mileage: 22,
    color: "White",
    createdAt: "2024-01-15",
  },
  {
    id: "v2",
    brand: "Hyundai",
    model: "Creta",
    year: 2024,
    category: "SUV",
    registrationNumber: "KA-01-CD-5678",
    fuelType: "Diesel",
    transmission: "Automatic",
    status: "Rented",
    pricePerDay: 2500,
    imageUrl: "/vehicles/creta.jpg",
    mileage: 17,
    color: "Black",
    createdAt: "2024-02-10",
  },
  {
    id: "v3",
    brand: "Honda",
    model: "City",
    year: 2023,
    category: "Sedan",
    registrationNumber: "KA-02-EF-9012",
    fuelType: "Petrol",
    transmission: "Automatic",
    status: "Available",
    pricePerDay: 2000,
    imageUrl: "/vehicles/city.jpg",
    mileage: 18,
    color: "Silver",
    createdAt: "2024-01-20",
  },
  {
    id: "v4",
    brand: "BMW",
    model: "3 Series",
    year: 2024,
    category: "Luxury",
    registrationNumber: "KA-01-GH-3456",
    fuelType: "Petrol",
    transmission: "Automatic",
    status: "Maintenance",
    pricePerDay: 8000,
    imageUrl: "/vehicles/bmw3.jpg",
    mileage: 14,
    color: "Blue",
    createdAt: "2024-03-01",
  },
  {
    id: "v5",
    brand: "Tata",
    model: "Nexon",
    year: 2024,
    category: "SUV",
    registrationNumber: "KA-03-IJ-7890",
    fuelType: "Electric",
    transmission: "Automatic",
    status: "Available",
    pricePerDay: 2200,
    imageUrl: "/vehicles/nexon.jpg",
    mileage: 0,
    color: "Red",
    createdAt: "2024-04-05",
  },
  {
    id: "v6",
    brand: "Toyota",
    model: "Innova Crysta",
    year: 2023,
    category: "SUV",
    registrationNumber: "KA-01-KL-2345",
    fuelType: "Diesel",
    transmission: "Manual",
    status: "Rented",
    pricePerDay: 3500,
    imageUrl: "/vehicles/innova.jpg",
    mileage: 15,
    color: "White",
    createdAt: "2024-02-15",
  },
  {
    id: "v7",
    brand: "Mercedes-Benz",
    model: "E-Class",
    year: 2024,
    category: "Luxury",
    registrationNumber: "KA-01-MN-6789",
    fuelType: "Petrol",
    transmission: "Automatic",
    status: "Available",
    pricePerDay: 12000,
    imageUrl: "/vehicles/eclass.jpg",
    mileage: 12,
    color: "Black",
    createdAt: "2024-05-10",
  },
  {
    id: "v8",
    brand: "Maruti Suzuki",
    model: "Baleno",
    year: 2023,
    category: "Hatchback",
    registrationNumber: "KA-02-OP-1234",
    fuelType: "Petrol",
    transmission: "Manual",
    status: "Available",
    pricePerDay: 1400,
    imageUrl: "/vehicles/baleno.jpg",
    mileage: 21,
    color: "Grey",
    createdAt: "2024-01-25",
  },
  {
    id: "v9",
    brand: "Hyundai",
    model: "Verna",
    year: 2024,
    category: "Sedan",
    registrationNumber: "KA-01-QR-5678",
    fuelType: "Petrol",
    transmission: "Automatic",
    status: "Rented",
    pricePerDay: 2200,
    imageUrl: "/vehicles/verna.jpg",
    mileage: 19,
    color: "Red",
    createdAt: "2024-03-15",
  },
  {
    id: "v10",
    brand: "Kia",
    model: "Seltos",
    year: 2024,
    category: "SUV",
    registrationNumber: "KA-03-ST-9012",
    fuelType: "Diesel",
    transmission: "Automatic",
    status: "Available",
    pricePerDay: 2800,
    imageUrl: "/vehicles/seltos.jpg",
    mileage: 16,
    color: "White",
    createdAt: "2024-04-20",
  },
  {
    id: "v11",
    brand: "Mahindra",
    model: "XUV700",
    year: 2023,
    category: "SUV",
    registrationNumber: "KA-01-UV-3456",
    fuelType: "Diesel",
    transmission: "Automatic",
    status: "Maintenance",
    pricePerDay: 3200,
    imageUrl: "/vehicles/xuv700.jpg",
    mileage: 14,
    color: "Blue",
    createdAt: "2024-02-28",
  },
  {
    id: "v12",
    brand: "Volkswagen",
    model: "Polo",
    year: 2022,
    category: "Hatchback",
    registrationNumber: "KA-02-WX-7890",
    fuelType: "Petrol",
    transmission: "Manual",
    status: "Available",
    pricePerDay: 1100,
    imageUrl: "/vehicles/polo.jpg",
    mileage: 19,
    color: "Silver",
    createdAt: "2024-01-10",
  },
];

// ==========================================
// CUSTOMERS
// ==========================================
export const customers: Customer[] = [
  {
    id: "c1",
    name: "Rajesh Kumar",
    phone: "+91 98765 43210",
    email: "rajesh.kumar@email.com",
    drivingLicenseNumber: "KA-0120230001234",
    verificationStatus: "Verified",
    address: "123 MG Road, Bangalore",
    createdAt: "2024-01-10",
  },
  {
    id: "c2",
    name: "Priya Sharma",
    phone: "+91 87654 32109",
    email: "priya.sharma@email.com",
    drivingLicenseNumber: "KA-0220230005678",
    verificationStatus: "Verified",
    address: "45 Koramangala, Bangalore",
    createdAt: "2024-01-15",
  },
  {
    id: "c3",
    name: "Amit Patel",
    phone: "+91 76543 21098",
    email: "amit.patel@email.com",
    drivingLicenseNumber: "MH-0120240001234",
    verificationStatus: "Pending",
    address: "78 Andheri West, Mumbai",
    createdAt: "2024-02-01",
  },
  {
    id: "c4",
    name: "Sneha Reddy",
    phone: "+91 65432 10987",
    email: "sneha.reddy@email.com",
    drivingLicenseNumber: "TN-0120230009012",
    verificationStatus: "Verified",
    address: "56 T Nagar, Chennai",
    createdAt: "2024-02-10",
  },
  {
    id: "c5",
    name: "Vikram Singh",
    phone: "+91 54321 09876",
    email: "vikram.singh@email.com",
    drivingLicenseNumber: "DL-0120230003456",
    verificationStatus: "Verified",
    address: "12 Connaught Place, Delhi",
    createdAt: "2024-03-01",
  },
  {
    id: "c6",
    name: "Ananya Iyer",
    phone: "+91 43210 98765",
    email: "ananya.iyer@email.com",
    drivingLicenseNumber: "KA-0320230007890",
    verificationStatus: "Rejected",
    address: "89 HSR Layout, Bangalore",
    createdAt: "2024-03-15",
  },
  {
    id: "c7",
    name: "Rohit Mehta",
    phone: "+91 32109 87654",
    email: "rohit.mehta@email.com",
    drivingLicenseNumber: "GJ-0120240002345",
    verificationStatus: "Verified",
    address: "34 SG Highway, Ahmedabad",
    createdAt: "2024-04-01",
  },
  {
    id: "c8",
    name: "Kavitha Nair",
    phone: "+91 21098 76543",
    email: "kavitha.nair@email.com",
    drivingLicenseNumber: "KL-0120230006789",
    verificationStatus: "Pending",
    address: "67 MG Road, Kochi",
    createdAt: "2024-04-15",
  },
];

// ==========================================
// BOOKINGS
// ==========================================
export const bookings: Booking[] = [
  {
    id: "b1",
    customerId: "c1",
    vehicleId: "v2",
    pickupDate: "2026-02-05",
    dropDate: "2026-02-12",
    status: "Active",
    totalAmount: 17500,
    createdAt: "2026-02-04",
    notes: "Corporate trip",
  },
  {
    id: "b2",
    customerId: "c2",
    vehicleId: "v6",
    pickupDate: "2026-02-08",
    dropDate: "2026-02-15",
    status: "Active",
    totalAmount: 24500,
    createdAt: "2026-02-07",
    notes: "Family vacation",
  },
  {
    id: "b3",
    customerId: "c4",
    vehicleId: "v9",
    pickupDate: "2026-02-10",
    dropDate: "2026-02-14",
    status: "Active",
    totalAmount: 8800,
    createdAt: "2026-02-09",
    notes: "Business travel",
  },
  {
    id: "b4",
    customerId: "c5",
    vehicleId: "v3",
    pickupDate: "2026-02-15",
    dropDate: "2026-02-20",
    status: "Reserved",
    totalAmount: 10000,
    createdAt: "2026-02-10",
    notes: "Weekend getaway",
  },
  {
    id: "b5",
    customerId: "c7",
    vehicleId: "v7",
    pickupDate: "2026-02-18",
    dropDate: "2026-02-22",
    status: "Reserved",
    totalAmount: 48000,
    createdAt: "2026-02-11",
    notes: "Wedding event",
  },
  {
    id: "b6",
    customerId: "c1",
    vehicleId: "v1",
    pickupDate: "2026-01-10",
    dropDate: "2026-01-15",
    status: "Completed",
    totalAmount: 6000,
    createdAt: "2026-01-09",
    notes: "Local sightseeing",
  },
  {
    id: "b7",
    customerId: "c3",
    vehicleId: "v5",
    pickupDate: "2026-01-20",
    dropDate: "2026-01-25",
    status: "Completed",
    totalAmount: 11000,
    createdAt: "2026-01-19",
    notes: "Airport transfer + city travel",
  },
  {
    id: "b8",
    customerId: "c2",
    vehicleId: "v8",
    pickupDate: "2026-01-05",
    dropDate: "2026-01-08",
    status: "Completed",
    totalAmount: 4200,
    createdAt: "2026-01-04",
    notes: "",
  },
  {
    id: "b9",
    customerId: "c6",
    vehicleId: "v10",
    pickupDate: "2026-02-01",
    dropDate: "2026-02-05",
    status: "Cancelled",
    totalAmount: 11200,
    createdAt: "2026-01-30",
    notes: "Customer requested cancellation",
  },
  {
    id: "b10",
    customerId: "c4",
    vehicleId: "v12",
    pickupDate: "2026-01-25",
    dropDate: "2026-01-28",
    status: "Completed",
    totalAmount: 3300,
    createdAt: "2026-01-24",
    notes: "Short trip",
  },
];

// ==========================================
// PAYMENTS
// ==========================================
export const payments: Payment[] = [
  {
    id: "p1",
    bookingId: "b1",
    amount: 17500,
    mode: "Card",
    status: "Paid",
    paidAt: "2026-02-04",
    transactionId: "TXN20260204001",
  },
  {
    id: "p2",
    bookingId: "b2",
    amount: 15000,
    mode: "UPI",
    status: "Partial",
    paidAt: "2026-02-07",
    transactionId: "TXN20260207002",
  },
  {
    id: "p3",
    bookingId: "b3",
    amount: 8800,
    mode: "Cash",
    status: "Paid",
    paidAt: "2026-02-09",
    transactionId: "TXN20260209003",
  },
  {
    id: "p4",
    bookingId: "b4",
    amount: 0,
    mode: "UPI",
    status: "Pending",
    paidAt: "",
    transactionId: "",
  },
  {
    id: "p5",
    bookingId: "b5",
    amount: 48000,
    mode: "Card",
    status: "Paid",
    paidAt: "2026-02-11",
    transactionId: "TXN20260211005",
  },
  {
    id: "p6",
    bookingId: "b6",
    amount: 6000,
    mode: "UPI",
    status: "Paid",
    paidAt: "2026-01-09",
    transactionId: "TXN20260109006",
  },
  {
    id: "p7",
    bookingId: "b7",
    amount: 11000,
    mode: "Card",
    status: "Paid",
    paidAt: "2026-01-19",
    transactionId: "TXN20260119007",
  },
  {
    id: "p8",
    bookingId: "b8",
    amount: 4200,
    mode: "Cash",
    status: "Paid",
    paidAt: "2026-01-04",
    transactionId: "TXN20260104008",
  },
  {
    id: "p9",
    bookingId: "b10",
    amount: 3300,
    mode: "UPI",
    status: "Paid",
    paidAt: "2026-01-24",
    transactionId: "TXN20260124009",
  },
];

// ==========================================
// MAINTENANCE RECORDS
// ==========================================
export const maintenanceRecords: MaintenanceRecord[] = [
  {
    id: "m1",
    vehicleId: "v4",
    serviceType: "Engine Repair",
    serviceDate: "2026-02-01",
    cost: 25000,
    description: "Engine overhaul and timing chain replacement",
    nextServiceDate: "2026-05-01",
    vendor: "BMW Service Center",
  },
  {
    id: "m2",
    vehicleId: "v11",
    serviceType: "Brake Service",
    serviceDate: "2026-02-05",
    cost: 8500,
    description: "Front and rear brake pad replacement",
    nextServiceDate: "2026-08-05",
    vendor: "Mahindra Authorized Service",
  },
  {
    id: "m3",
    vehicleId: "v1",
    serviceType: "General Service",
    serviceDate: "2026-01-15",
    cost: 4500,
    description: "Regular 10,000 km service with oil and filter change",
    nextServiceDate: "2026-07-15",
    vendor: "Maruti Suzuki Arena",
  },
  {
    id: "m4",
    vehicleId: "v6",
    serviceType: "AC Service",
    serviceDate: "2026-01-20",
    cost: 3200,
    description: "AC gas refill and condenser cleaning",
    nextServiceDate: "2026-07-20",
    vendor: "CoolTech Auto AC",
  },
  {
    id: "m5",
    vehicleId: "v2",
    serviceType: "Tire Replacement",
    serviceDate: "2025-12-10",
    cost: 18000,
    description: "All four tires replaced with Michelin Primacy",
    nextServiceDate: "2026-12-10",
    vendor: "Michelin Tire Shop",
  },
  {
    id: "m6",
    vehicleId: "v7",
    serviceType: "General Service",
    serviceDate: "2026-01-25",
    cost: 15000,
    description: "20,000 km scheduled maintenance service",
    nextServiceDate: "2026-07-25",
    vendor: "Mercedes-Benz Service",
  },
  {
    id: "m7",
    vehicleId: "v5",
    serviceType: "Battery Replacement",
    serviceDate: "2025-11-20",
    cost: 12000,
    description: "12V auxiliary battery replacement",
    nextServiceDate: "2027-11-20",
    vendor: "Tata EV Service Center",
  },
  {
    id: "m8",
    vehicleId: "v8",
    serviceType: "Oil Change",
    serviceDate: "2026-02-08",
    cost: 2500,
    description: "Synthetic oil change with filter",
    nextServiceDate: "2026-05-08",
    vendor: "Quick Lube Express",
  },
];

// ==========================================
// BUSINESS SETTINGS
// ==========================================
export const businessSettings: BusinessSettings = {
  businessName: "SpeedWheels Car Rentals",
  gstPercentage: 18,
  currency: "INR",
  rentalRules:
    "1. Valid driving license required for all rentals.\n2. Minimum rental period is 1 day.\n3. Fuel must be refilled to pick-up level on return.\n4. Maximum 300 km/day included; ₹12/km extra.\n5. Late returns charged at 1.5x daily rate per hour.\n6. Security deposit of ₹5,000 required for all bookings.",
  cancellationPolicy:
    "1. Free cancellation up to 24 hours before pickup.\n2. 50% refund for cancellations within 24 hours.\n3. No refund for no-shows.\n4. Modifications allowed up to 12 hours before pickup.",
  contactEmail: "admin@speedwheels.in",
  contactPhone: "+91 80 4567 8900",
  address: "42, 100 Feet Road, Indiranagar, Bangalore - 560038",
};

// ==========================================
// DASHBOARD DATA
// ==========================================
export const dashboardStats: DashboardStats = {
  totalVehicles: 12,
  availableVehicles: 6,
  activeRentals: 3,
  monthlyRevenue: 134500,
  pendingPayments: 2,
  totalCustomers: 8,
};

export const monthlyRevenue: MonthlyRevenue[] = [
  { month: "Sep", revenue: 89000, bookings: 8 },
  { month: "Oct", revenue: 112000, bookings: 11 },
  { month: "Nov", revenue: 98000, bookings: 9 },
  { month: "Dec", revenue: 145000, bookings: 14 },
  { month: "Jan", revenue: 124500, bookings: 12 },
  { month: "Feb", revenue: 134500, bookings: 10 },
];

export const vehicleUtilization: VehicleUtilization[] = [
  { category: "Hatchback", utilized: 65, idle: 35 },
  { category: "Sedan", utilized: 78, idle: 22 },
  { category: "SUV", utilized: 82, idle: 18 },
  { category: "Luxury", utilized: 55, idle: 45 },
];

// Helper functions
export function getCustomerById(id: string): Customer | undefined {
  return customers.find((c) => c.id === id);
}

export function getVehicleById(id: string): Vehicle | undefined {
  return vehicles.find((v) => v.id === id);
}

export function getBookingById(id: string): Booking | undefined {
  return bookings.find((b) => b.id === id);
}

export function getBookingsByCustomerId(customerId: string): Booking[] {
  return bookings.filter((b) => b.customerId === customerId);
}

export function getMaintenanceByVehicleId(
  vehicleId: string,
): MaintenanceRecord[] {
  return maintenanceRecords.filter((m) => m.vehicleId === vehicleId);
}

export function getPaymentByBookingId(bookingId: string): Payment | undefined {
  return payments.find((p) => p.bookingId === bookingId);
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}
